### ISSUE TITLE
Silent fails on incorrect yaml

### ISSUE THREAD

**Issue by dantefromhell** [devops-kung-fu/hookz#111]
## Issue

If the YAML syntax is invalid `hookz initialise` does not create any hook.
`hookz reset` on an invalid YAML file deletes all existing hooks, including those that have no syntax errors.

It would be great if an error that the YAML file is invalid would be displayed instead.

## Steps to reproduce
Tested release: 2.4.2

Example config
```yaml
  version: 2.4.2

  hooks:
    - type: pre-commit
      actions:
        - name: "Git Pull (Ensure there are no upstream changes)"
          exec: git
          args: ["pull"]
    - type: post-commit
      actions:
        - name: "Mark all done"
          exec: echo
          args: ["-e" "[x] Successfully committed upstream"]
```
yields the following results
```shell
$ hookz reset --verbose-output

█ █ █▀█ █▀█ █▄▀ ▀█
█▀█ █▄█ █▄█ █ █ █▄

DKFM - DevOps Kung Fu Mafia
https://github.com/devops-kung-fu/hookz
Version: 2.4.2

■ Resetting Hooks
■ Done
$ ls -la .git/hooks
total 64
drwxr-xr-x 1 dantefromhell users  530 Nov 29 15:12 .
drwxr-xr-x 1 dantefromhell users  182 Nov 29 15:00 ..
-rwxr-xr-x 1 dantefromhell users  536 Nov 29 13:22 applypatch-msg.sample
-rwxr-xr-x 1 dantefromhell users  954 Nov 29 13:22 commit-msg.sample
-rwxr-xr-x 1 dantefromhell users 4706 Nov 29 13:22 fsmonitor-watchman.sample
-rw-r--r-- 1 dantefromhell users   64 Nov 29 15:12 hookz.shasum
-rwxr-xr-x 1 dantefromhell users  247 Nov 29 13:22 post-update.sample
-rwxr-xr-x 1 dantefromhell users  482 Nov 29 13:22 pre-applypatch.sample
-rwxr-xr-x 1 dantefromhell users 1701 Nov 29 13:22 pre-commit.sample
-rwxr-xr-x 1 dantefromhell users  474 Nov 29 13:22 pre-merge-commit.sample
-rwxr-xr-x 1 dantefromhell users 1703 Nov 29 13:22 prepare-commit-msg.sample
-rwxr-xr-x 1 dantefromhell users 1432 Nov 29 13:22 pre-push.sample
-rwxr-xr-x 1 dantefromhell users 5007 Nov 29 13:22 pre-rebase.sample
-rwxr-xr-x 1 dantefromhell users  602 Nov 29 13:22 pre-receive.sample
-rwxr-xr-x 1 dantefromhell users 2841 Nov 29 13:22 push-to-checkout.sample
-rwxr-xr-x 1 dantefromhell users 3708 Nov 29 13:22 update.sample
```
